export const userMenuStyles = {
  iconButton: { padding: '0px' },
  accountCircle: { fontSize: '60px' },
  menu: { marginTop: 50 },
  menuItem: { color: 'grey' },
  assignment: { marginRight: 20 },
  language: { marginRight: 20 },
  connection: { marginRight: 20 },
  projects: { marginRight: 20 },
  exitToApp: { marginRight: 20 },
  extendedMenu1: { marginLeft: -170, marginTop: 100 },
  extendedMenu2: { marginLeft: -170, marginTop: 150 },
  extendedMenu3: { marginLeft: -170, marginTop: 200 },
  reactFragmentDiv: { borderRadius: '50%', width: 10, height: 10 },
  connectionTypography: { fontSize: 16, textTransform: 'uppercase' },
  infoDiv: { float: 'right', marginRight: '20px' },
  projectTypography: { textTransform: 'uppercase', fontWeight: 'bold', marginRight: 4, color: 'grey', fontSize: 12 },
  projRoleSeparator: { fontSize: 14, fontWeight: 'lighter', marginTop: -3 },
  roleTypography: { textTransform: 'uppercase', color: 'white', marginLeft: 4, marginRight: 4, fontSize: 12 },
  projectInfo: { display: 'flex', marginBottom: 4 },
  userNameTypography: { textTransform: 'uppercase', color: 'black', fontSize: 12, }
};